/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author asyed
 */
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.IOException;
import java.sql.SQLException;
//import java.util.stream.Collectors;
//import java.util.stream.Stream;


public class HomePage2 extends javax.swing.JFrame {
    
    private int leaf_count;
    private boolean qryValidFlg;
    private ArrayList<String> leaf_list = new ArrayList<String>();
    private String URL;
    private String username;
    private String password;
    
    public HomePage2(){
        this.qryValidFlg = false;
        this.leaf_count = 0;
        initComponents();
        jTree1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jButton13.setVisible(false);
        jPanel11.setVisible(false);
        jPanel12.setVisible(false);
        this.setLocationRelativeTo(null);
        //System.out.println(System.getProperty("user.dir"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton8 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 85));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 120, 50));

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setText("Get Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel8.setBackground(new java.awt.Color(36, 47, 85));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setPreferredSize(new java.awt.Dimension(320, 600));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 320));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 110, 40));

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setText("View Data");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 110, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html>SELECT TABLES/VIEWS FROM THE LIST</html>");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 470));

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("Select");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 110, 40));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel5.setBackground(new java.awt.Color(36, 47, 85));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(320, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Oracle Database<br>Connection Details</html>");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 60));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>Enter Database details (URL) in the below format:</html>");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setText("jdbc:oracle:thin:@localhost:1521:orcl");
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 290, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Connect");
        jButton7.setToolTipText("");
        jButton7.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton7.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(60, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 100, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 30));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, 30));

        jPasswordField1.setToolTipText("");
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>Hostname:Port:SID  (or)<br>  Hostname:Port/Service Name <>");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 290, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Exit");
        jButton5.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(60, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, -1, 120));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 80, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Next");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 80, 40));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setText("SELECT DATA SOURCE TYPE");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 360, 40));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Move Data directly from Tables/Views");
        jRadioButton3.setBorder(null);
        jPanel6.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 350, 50));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton4.setText("Move data using a SQL query");
        jRadioButton4.setBorder(null);
        jPanel6.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 290, 50));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton5.setText("Import whole schema");
        jRadioButton5.setBorder(null);
        jPanel6.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 290, 50));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, -1, 120));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Selected Tables/Views");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 270, 30));

        jButton11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton11.setText("START");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 90, 40));

        jButton10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 90, 40));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane4.setViewportView(jLabel15);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 400, 200));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 400, 200));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setText("Click 'Start' to load the data");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, 30));

        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton13.setText("VALIDATE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 130, 40));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 430, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setText("Selected File Path");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 80));

        jButton15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 120, 50));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setText("Specify Target HDFS Path");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 20));
        jPanel10.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 430, 30));

        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton16.setText("Start");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, 50));

        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jButton17.setText("View Data");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        jPanel9.setBackground(new java.awt.Color(36, 47, 85));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setFocusCycleRoot(true);
        jPanel9.setPreferredSize(new java.awt.Dimension(320, 500));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, 50));

        jButton14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton14.setText("Browse File");
        jButton14.setBorderPainted(false);
        jButton14.setMaximumSize(new java.awt.Dimension(111, 20));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 50));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel11.setBackground(new java.awt.Color(36, 47, 85));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setFocusCycleRoot(true);
        jPanel11.setPreferredSize(new java.awt.Dimension(320, 500));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton20.setText("Exit");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, 50));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setText("Importing whole schema tables..");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 420, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 80));

        jButton22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton22.setText("Back");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 120, 50));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setText("Specify Target HDFS Path");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 20));
        jPanel12.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 430, 30));

        jButton23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton23.setText("Start");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, 50));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, -1, 120));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DATA LOAD AUTOMATION");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 70));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html>This tool enables us to automate the Data Load Process from Any Data Source to Hadoop Platform using Spark/Sqoop</html>");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 420, 80));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel23.setText("<html>\n<h1><b>Features</b></h1>\n<br>\n <i> - Highly Compressed</i><br>\n <i> - Database Offload Engine</i><br>\n <i> - Heterogenous Sources</i><br>\n <i> - Better Performance</i><br>\n <i> - Better Performance</i><br>\n <i> - Smart Executor</i><br>\n <i> - Streaming Data</i><br>\n</html>");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 400, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        jPanel3.setBackground(new java.awt.Color(36, 47, 85));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("File");
        jRadioButton1.setMaximumSize(new java.awt.Dimension(100, 25));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(100, 25));
        jRadioButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, 40));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Database");
        jRadioButton2.setMaximumSize(new java.awt.Dimension(100, 25));
        jRadioButton2.setMinimumSize(new java.awt.Dimension(100, 25));
        jRadioButton2.setPreferredSize(new java.awt.Dimension(100, 25));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(60, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 90, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SOURCE TYPE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBorder(new javax.swing.border.MatteBorder(null));
        jList1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "ORACLE", "MY SQL" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 250, 160));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("SELECT DATABASE TYPE");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 310, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(60, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 90, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, -1, 120));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("SELECT FILE TYPE");
        DefaultListModel file_type=new DefaultListModel();
        file_type.addElement("TEXT/CSV FILE");
        file_type.addElement("JSON FILE");
        file_type.addElement("XML FILE");
        jList1.setModel(file_type);
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("SELECT DATABASE TYPE");
        DefaultListModel db_type=new DefaultListModel();
        db_type.addElement("ORACLE");
        db_type.addElement("MY SQL");
        jList1.setModel(db_type);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setActionCommand(jRadioButton1.getText());
        jRadioButton2.setActionCommand(jRadioButton2.getText());
        //System.out.println(jList1.getSelectedValue());
        if("Database".equals(buttonGroup1.getSelection().getActionCommand()) && "ORACLE".equals(jList1.getSelectedValue())){
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(true);
            jPanel6.setVisible(true);
            jLabel7.setText("<html>Oracle Database<br>Connection Details</html>");
            jLabel11.setText("<html>Hostname:Port:SID  (or)<br>  Hostname:Port/Service Name </html>");
            jTextField1.setText("jdbc:oracle:thin:@localhost:1521:orcl");
        }
        else if("Database".equals(buttonGroup1.getSelection().getActionCommand()) && "MY SQL".equals(jList1.getSelectedValue())){
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(true);
            jPanel6.setVisible(true);
            jLabel7.setText("<html>MySQL Database<br>Connection Details</html>");
            jLabel11.setText("<html>hostname:port/databasename</html>");
            jTextField1.setText("jdbc:mysql://quickstart.cloudera:3306/retail_db");
        }
        else if("File".equals(buttonGroup1.getSelection().getActionCommand()) && "TEXT/CSV FILE".equals(jList1.getSelectedValue())){
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel9.setVisible(true);
            jPanel10.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null,  "This is not configured yet. Please select some other option.");
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void display_jTree(JTree tree, String user, String[] ta, String[] va){
        
        DefaultTreeModel model=(DefaultTreeModel) tree.getModel();
        DefaultMutableTreeNode root=(DefaultMutableTreeNode) model.getRoot();
        //System.out.println("The root is : "+root);
        root.removeAllChildren(); //this removes all nodes
        model.reload();
        
        root.setUserObject(user.toUpperCase());
        root.add(new DefaultMutableTreeNode("TABLES"));
        root.add(new DefaultMutableTreeNode("VIEWS"));
        model.reload();
        
        Enumeration children = root.children();
        while(children.hasMoreElements()){
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) children.nextElement();
            if(node.toString().equals("TABLES")){
                for(int i=0;i<ta.length;i++)
                    node.add(new DefaultMutableTreeNode(ta[i]));
            }
            else if(node.toString().equals("VIEWS")){
                for (String va1 : va) {
                    node.add(new DefaultMutableTreeNode(va1));
                }
            }
        }
        model.reload();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jLabel12.setText("Status: Connecting...");
        URL=jTextField1.getText();
        username=jTextField2.getText();
        password=new String(jPasswordField1.getPassword());
        jTree1.setVisible(false);
        String db_name=URL.substring(URL.lastIndexOf('/')+1);
        
        try{
            
            if(jList1.getSelectedValue()=="ORACLE")
                Class.forName("oracle.jdbc.driver.OracleDriver");
            else if (jList1.getSelectedValue()=="MY SQL")
                Class.forName("com.mysql.jdbc.Driver");
            
            Connection con=DriverManager.getConnection(URL,username,password);
            System.out.println("Status: Connection succeeded!");
            jLabel12.setText("Status: Connection succeeded!");
            Statement stmt=con.createStatement();
            
            ResultSet rs_tbl_count = null,rs_vw_count = null,rs_tbl_data = null,rs_vw_data = null;
            int tbl_count,vw_count;
            String[] tbl_data = null;
            String[] vw_data = null;
            
            if(jList1.getSelectedValue()=="ORACLE"){
                rs_tbl_count=stmt.executeQuery("SELECT COUNT(*) FROM USER_TABLES");
                rs_tbl_count.next();
                tbl_count=rs_tbl_count.getInt(1);
                tbl_data=new String[tbl_count];
                
                rs_vw_count=stmt.executeQuery("SELECT COUNT(*) FROM USER_VIEWS");
                rs_vw_count.next();
                vw_count=rs_vw_count.getInt(1);
                vw_data=new String[vw_count];
                
                rs_tbl_data=stmt.executeQuery("SELECT TABLE_NAME FROM USER_TABLES ORDER BY 1");
                for(int i=0;rs_tbl_data.next();i++)
                    tbl_data[i]=rs_tbl_data.getString(1);
                
                rs_vw_data=stmt.executeQuery("SELECT VIEW_NAME FROM USER_VIEWS ORDER BY 1");
                for(int i=0;rs_vw_data.next();i++)
                    vw_data[i]=rs_vw_data.getString(1);
            }
            else if (jList1.getSelectedValue()=="MY SQL"){
                String qry_tbl_count="SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE 'BASE TABLE' AND TABLE_SCHEMA='"+db_name+"'";
                rs_tbl_count=stmt.executeQuery(qry_tbl_count);
                //.out.println("Table count query executed!");
                rs_tbl_count.next();
                tbl_count=rs_tbl_count.getInt(1);
                tbl_data=new String[tbl_count];
                
                String qry_vw_count="SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE 'VIEW' AND TABLE_SCHEMA='"+db_name+"'";
                rs_vw_count=stmt.executeQuery(qry_vw_count);
                //System.out.println("View count query executed!");
                rs_vw_count.next();
                vw_count=rs_vw_count.getInt(1);
                vw_data=new String[vw_count];
                
                
                String qry_tbl_data="SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE 'BASE TABLE' AND TABLE_SCHEMA='"+db_name+"'";
                rs_tbl_data=stmt.executeQuery(qry_tbl_data);
                //System.out.println("Table data query executed!");
                for(int i=0;rs_tbl_data.next();i++)
                    tbl_data[i]=rs_tbl_data.getString(1);
                
                String qry_vw_data="SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE 'VIEW' AND TABLE_SCHEMA='"+db_name+"'";
                rs_vw_data=stmt.executeQuery(qry_vw_data);
                //System.out.println("View data query executed!");
                for(int i=0;rs_vw_data.next();i++)
                    vw_data[i]=rs_vw_data.getString(1);
            }
            
            //String[] tbl_data=new String[tbl_count];
            //String[] vw_data=new String[vw_count];
            jTree1.setVisible(true);
            
            display_jTree(jTree1,username,tbl_data,vw_data);
            //System
        }
        catch(Exception e){
            jLabel12.setText("<html>"+ "Status: "+ e.getMessage() +"</html>");
            //System.out.println(e.getMessage());
            //jTree1.setModel(null);
        }  
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
        
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(jLabel12.getText().equals("Status: Connection succeeded!")){
            
            jRadioButton3.setActionCommand(jRadioButton3.getText());
            jRadioButton4.setActionCommand(jRadioButton4.getText());
            jRadioButton5.setActionCommand(jRadioButton4.getText());
            
            if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton3.getText())){
                jPanel5.setVisible(false);
                jPanel6.setVisible(false);
                jPanel7.setVisible(true);
                jPanel8.setVisible(true);
                jScrollPane3.setVisible(false);
                jScrollPane4.setVisible(true);
                jScrollPane2.setVisible(true);
                jButton18.setVisible(true);
                jButton19.setVisible(true);
                jButton13.setVisible(false);
                
                jLabel14.setText("Selected Tables/Views");
                jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                jLabel6.setText("<html>SELECT TABLES/VIEWS FROM THE LIST</html>");
                jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            }
            else if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton4.getText())){
                jPanel5.setVisible(false);
                jPanel6.setVisible(false);
                jPanel7.setVisible(true);
                jPanel8.setVisible(true);
                jButton13.setVisible(true);
                
                jLabel6.setText("<html>Write the SQL query in the Text Area given</html>");
                jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 24));
                jLabel6.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                jScrollPane2.setVisible(false);
                jScrollPane4.setVisible(false);
                jScrollPane3.setVisible(true);
                jButton18.setVisible(false);
                jButton19.setVisible(false);
                jLabel14.setText("Write/Paste your query here");
            }
            else if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton5.getText())){
                jPanel5.setVisible(false);
                jPanel6.setVisible(false);
                jPanel11.setVisible(true);
                jPanel12.setVisible(true);
                jButton13.setVisible(false);
                
                /*
                jLabel6.setText("<html>Write the SQL query in the Text Area given</html>");
                jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 24));
                jLabel6.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                jScrollPane2.setVisible(false);
                jScrollPane4.setVisible(false);
                jScrollPane3.setVisible(true);
                jButton18.setVisible(false);
                jButton19.setVisible(false);
                jLabel14.setText("Write/Paste your query here");
                */
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Could not connect to database!", "Oops!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton3.getText()))
        
        String tgt_path="/user/cloudera/";
        char overwrite_flg='Y';
        byte parallel_count=1;
        char is_incr='Y';
        String incr_column="";
        String last_ext_date="";
        String file_data="";
        
        //.setActionCommand(jRadioButton3.getText());
        //jRadioButton4.setActionCommand(jRadioButton4.getText());
        
        if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton3.getText())){
            try {
                File directory = new File(System.getProperty("user.dir") + File.separator + "FileInputDir");
                if (!directory.exists())
                    directory.mkdir();
                String FILENAME =directory.getPath() + File.separator + "UI_Metadata.txt";
                
                if(leaf_list.isEmpty())
                    JOptionPane.showMessageDialog(null, "No Tables/Views selected!", "Error!", JOptionPane.INFORMATION_MESSAGE);
                else{
                    FileWriter writer = new FileWriter(FILENAME);
                    BufferedWriter bw = new BufferedWriter(writer);
                    //bw.write(filename);
                    for(int sno=1;sno<=leaf_list.size();sno++){
                        file_data=sno+"|DATABASE|"+leaf_list.get(sno-1)+"|"
                                +tgt_path+"|"+overwrite_flg+"|"+parallel_count+"|"
                                +is_incr+"|"+incr_column+"|"+last_ext_date+"|"
                                +URL+"|"+username+"|"+password;
                        bw.write(file_data);
                        if(sno<leaf_list.size())
                            bw.write("\n");
                        //System.out.println(leaf_list.get(sno-1));
                    }
                    bw.close();
                    writer.close();
                    File f = new File(FILENAME);
                    String absolutePath = f.getAbsolutePath();
                    Client.executePython(absolutePath);
                    JOptionPane.showMessageDialog(null,  "Successfully written to File");
                    //System.out.println(leaf_list.size());
                }
            } catch (IOException ex) {
                Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(buttonGroup2.getSelection().getActionCommand().equals(jRadioButton4.getText())){
            try {
                File directory = new File(System.getProperty("user.dir") + File.separator + "FileInputDir");
                if (!directory.exists())
                    directory.mkdir();
                String FILENAME =directory.getPath() + File.separator + "UI_Metadata.txt";
                FileWriter writer = new FileWriter(FILENAME);
                BufferedWriter bw = new BufferedWriter(writer);
                //bw.write(filename);
                
                file_data="1|DATABASE|"+jTextArea2.getText().replaceAll("\n", " ")+"|"
                        +tgt_path+"|"+overwrite_flg+"|"+parallel_count+"|"
                        +is_incr+"|"+incr_column+"|"+last_ext_date+"|"
                        +URL+"|"+username+"|"+password;
                bw.write(file_data);
                
                bw.close();
                writer.close();
                System.out.println(jTextArea2.getText().replaceAll("\n", " "));
                File f = new File(FILENAME);
                String absolutePath = f.getAbsolutePath();
                Client.executePython(absolutePath);
                JOptionPane.showMessageDialog(null,  "Successfully written to File");
                
            } catch (IOException ex) {
                Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
    }//GEN-LAST:event_jButton12ActionPerformed
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField3.setText(filename);
        
    }//GEN-LAST:event_jButton14ActionPerformed
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(true);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel10.setVisible(false);
        jPanel10.setVisible(false);
        jPanel9.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed
    
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:\\
        try {
            String projectPath=System.getProperty("user.dir");
            File directory = new File(projectPath + File.separator + "FileInputDir");
            if (!directory.exists())
                directory.mkdir();
            
            String FILENAME =directory.getPath() + File.separator + "UI_Metadata.txt";
            FileWriter writer = new FileWriter(FILENAME);
            BufferedWriter bw = new BufferedWriter(writer);
            String file_out_String="1|"+jTextField3.getText()+"|"+jTextField4.getText();
            bw.write(file_out_String);
            File f = new File(FILENAME);
            String absolutePath = f.getAbsolutePath();
            bw.close();
            writer.close();
            Client.executePython(absolutePath);
            JOptionPane.showMessageDialog(null,  "Successfully written to File");
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton16ActionPerformed
    
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
        try {
            String filename=jTextField3.getText();
            FileReader  reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            jTextArea1.read (br ,null);
            jTextArea1.requestFocusInWindow();
            JOptionPane.showMessageDialog(null,jTextArea1);
            
            br.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select a valid file!", "Error!", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton17ActionPerformed
    
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This doesn't work yet.. Sorry!", "Oops!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton18ActionPerformed
    
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model=(DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode root=(DefaultMutableTreeNode) model.getRoot();
        String selected_list="<html><ul>";
        jLabel15.setText("");
        leaf_list.clear();
        leaf_count=0;
        try{
            TreePath[] paths = jTree1.getSelectionPaths();
            DefaultMutableTreeNode selectedNode;
            for (TreePath path : paths) {
                //for(int i=0;i<paths.length;i++){
                selectedNode=(DefaultMutableTreeNode) path.getLastPathComponent();
                if(selectedNode.isLeaf()){
                    leaf_count++;
                    selected_list=selected_list+"<li>"+selectedNode.toString()+"</li>";
                    leaf_list.add(selectedNode.toString());
                }
            }
            
            selected_list=selected_list+"</ul></html>";
            //for(String s : leaf_list)
            //    System.out.println(s);
            if (leaf_count==0)
                JOptionPane.showMessageDialog(null, "No tables/Views selected!", "Oops!", JOptionPane.INFORMATION_MESSAGE);
            else
                jLabel15.setText(selected_list);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No tables/Views selected!", "Oops!", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed
    
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String URL=jTextField1.getText();
        String username=jTextField2.getText();
        String password=new String(jPasswordField1.getPassword());
        if(jTextArea2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your query... ");
            
        }
        else {
            try {
                
                if(jList1.getSelectedValue()=="ORACLE")
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                else if (jList1.getSelectedValue()=="MY SQL")
                    Class.forName("com.mysql.jdbc.Driver");
                
                Connection con=DriverManager.getConnection(URL,username,password);
                Statement stmt=con.createStatement();
                String SQL =jTextArea2.getText();
                String SQL_VALID= "select * from ("+ SQL + ") where 1=2";
                System.out.println(SQL_VALID);
                try {
                    ResultSet query_result=stmt.executeQuery(SQL_VALID);
                    // System.out.println(query_result);
                    query_result.next();
                    JOptionPane.showMessageDialog(null, "Your SQL Query looks Good");
                    query_result.close();
                    stmt.close();
                    con.close();
                    
                    //             String query = query_result.getNString(1);
                    //           JOptionPane.showMessageDialog(null,query, "Oops!", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Oops!", JOptionPane.INFORMATION_MESSAGE);
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
            }
            //  JOptionPane.showMessageDialog(null, "This doesn't work yet.. Sorry!", "Oops!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(null, "Do you really want to Exit?", "Exit Data-Ing", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, null, null)==0)
            System.exit(1);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(true);
        jPanel6.setVisible(true);
        jPanel11.setVisible(false);
        jPanel12.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
